CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Users (
   ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
   Username VARCHAR(255) NOT NULL UNIQUE,
   Email VARCHAR(255) NOT NULL UNIQUE,
   HashedPassword TEXT,
   CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);