version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      # decomment this to have persistent data
      #- pgdata:/var/lib/postgresql/data
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
      - ./custom-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh

volumes:
  pgdata:
    driver: local
