import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("../saved-new-pretrain")
tokenizer = AutoTokenizer.from_pretrained("../saved-new-pretrain")

comments = [
    "former versace store clerk sues over secret 'black code' for minority shoppers",
        "the 'roseanne' revival catches up to our thorny political mood, for better and worse",
        "mom starting to fear son's web series closest thing she will have to grandchild",
        "boehner just wants wife to listen, not come up with alternative debt-reduction ideas",
        "j.k. rowling wishes snape happy birthday in the most magical way",
        "advancing the world's women",
        "the fascinating case for eating lab-grown meat",
        "this ceo will send your kids to school, if you work for his company",
        "top snake handler leaves sinking huckabee campaign",
        "friday's morning email: inside trump's presser for the ages",
        "airline passengers tackle man who rushes cockpit in bomb threat",
        "facebook reportedly working on healthcare features and apps",
        "north korea praises trump and urges us voters to reject 'dull hillary'",
        "actually, cnn's jeffrey lord has been 'indefensible' for a while",
        "barcelona holds huge protest in support of refugees",
        "nuclear bomb detonates during rehearsal for 'spider-man' musical",
        "cosby lawyer asks why accusers didn't come forward to be smeared by legal team years ago",
        "stock analysts confused, frightened by boar market",
        "bloomberg's program to build better cities just got bigger",
        "craig hicks indicted",
        "courtroom sketch artist has clear manga influences",
        "trump assures nation that decision for syrian airstrikes came after carefully considering all his passing whims",
        "qatar deporting dutch woman who reported she was drugged and raped",
        "this is why you shouldn't go to the circus",
        "ted cruz hits the panic button: 'we could lose both houses of congress'",
        "why writers must plan to be surprised",
        "obama visits arlington national cemetery to honor veterans",
        "ex-con back behind bar",
        "after careful consideration, bush recommends oil drilling",
        "remembrance is the beginning of the task",
        "allies: islamist motive for killing nemtsov is nonsense",
        "gillian jacobs on what it's like to kiss adam brody",
        "uber vows to repay nyc drivers 'tens of millions' after tax snafu",
        "apple may have poached electric motorcycle company to death",
        "drug-resistant bacteria often lurk in children's, dogs' sandboxes",
        "if you see a muslim at the airport",
        "giant altoid heading toward earth",
        "'moana' sails straight to the top of the box office with massive $81.1 million opening",
        "selig counted money while baseball lost the next generation of fans",
        "robin williams inflicted on holiday moviegoers for eighth straight year",
        "devin nunes vows to 'never' reveal source of surveillance claims",
        "scott used to stop breathing nearly 40 times an hour. this device changed his life",
        "rescuers heroically help beached garbage back into ocean",
        "medics drop soccer player from stretcher; he's ticked",
        "give the gift of play this holiday season",
        "christian bale visits sikh temple victims",
        "spicer denies that ending maternity care guarantee would mean women pay more for health care",
        "'right to live life in complete, stunned horror,' added to constitution",
        "nasa now almost positive mars is rocky",
        "monster undeterred by night-light",
        "diy: sports equipment closet",
        "1 dead, 3 injured in shooting at t.i. concert in nyc",
        "longtime teacher retires without changing a single student's life",
        "donald trump heading for a series of wins in the northeast, polls say",
        "donald trump wouldn't have had the ready cash to self-finance entire campaign \u2014 analysis",
        "new 'star wars' film once again disappoints die-hard nien nunb fans",
        "bats shooed out of nation's waterslide tunnels in preparation for summer",
        "mobile news crew reports on own van breaking down",
        "un rights chief calls humanitarian situation in syria 'an outrage'",
        "how to track santa claus' flight around the world this christmas eve",
        "obama has colorado appraised",
        "trouble again in tv's africa",
        "brita unveils new in-throat water filters",
        "report: john grisham slowly but surely climbing list of greatest living american authors",
        "ghost can't make a simple cup of coffee without everyone freaking out",
        "tupperware will never truly recover from red curry leftovers",
        "one of the planet's most powerful forces for change? an adolescent girl",
        "how does draymond green take his game to the next level? by tuning in to the wnba",
        "area woman said 'sorry' 118 times yesterday",
        "ryan lochte apologizes for behavior in rio",
        "north dakota not heard from in 48 hours",
        "4 lessons prison taught me about power and control",
        "sick fucks line up to gape at dead body",
        "what is america's first muslim fraternity really like?",
        "the vicious knot of syria, the untangling process contains solutions in our time",
        "this congressman thinks we can fix the economy by drinking beer",
        "breast implants found to cause problems in laboratory mice",
        "trump orders strikes on syria in retaliation for chemical attack",
        "ceo's funeral a networking dream",
        "year-round schooling: how it would help minority students",
        "90 zen teachers pledge to change culture that fosters abuse",
        "nypd weighs allowing chokeholds following eric garner death",
        "sonny bono foundation prevents at-risk youths from skiing into trees",
        "pope francis reminds the world that caring for the earth is everyone's responsibility",
        "6-year-old cries when told mtm productions kitten dead by now",
        "ex-boyfriend just thought he'd check in and throw entire day off",
        "doctors restore ken burns' full-color vision after removing massive tumor from filmmaker's visual cortex",
        "'gravity' & '12 years a slave' tie at 2014 pga awards",
        "for national coming out day, 150 lgbtq sports people who have come out in the last year",
        "john oliver lays out the most disturbing ways in which trump impacts america",
        "house gop crackdown continues",
        "'i must make sure you have the skills to please my grandson,' says queen elizabeth disrobing before meghan markle",
        "man visiting hometown amazed to find all his childhood insecurities still there",
        "look: world cup star attacked by giant bug",
        "clinton becomes first president to clear 18 feet in pole vault",
        "hunter s. thompson shoots mouth off one last time",
        "inhofe's grand climate conspiracy theory: it's all about barbra streisand",
        "5 questions i wish younger people would stop asking me",
        "albuquerque shooter on the loose; gunman leaves 1 dead, 3 injured",
        "what it's like to lose everything in a flood",
        "demi lovato drops emotional 'nightingale' music vid",
        "Batman: Under the Red Hood",
        "Oh lordy we cant have dumb people teach their own kids, it should only be the governments job",
        "Nah Bernies been booling since the civil rights movement",
        "Only took me 1 hour.",
        "It's like if Red Hood and Spider-Man did a fusion ha.",
        "Now you know how Trump got elected."
]

values = [
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        1,
        1,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        1,
        1,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        1,
        0,
        0
]

tokenized_comments = tokenizer(comments, return_tensors="pt", truncation=True, padding=True, max_length=512)

model.eval()
with torch.no_grad():
    results = model(**tokenized_comments)

resulted_logits = results.logits
probabilities = torch.nn.functional.softmax(resulted_logits, dim=-1)
predicted_classes = torch.argmax(probabilities, dim=-1).numpy()

index = 0
for text, predicted_class, prob in zip(comments, predicted_classes, probabilities):
    response = "sarcastic" if predicted_class == 1 else "not sarcastic"
    value = values[index]
    index += 1
    print(f"Text: {text} Prediction: {response} Real value: {value} (Prob: {prob[predicted_class].item():.2f})")