import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

model = AutoModelForSequenceClassification.from_pretrained("../saved-fifth-pretrain")
tokenizer = AutoTokenizer.from_pretrained("../saved-fifth-pretrain")

comments = [
    "Oh, another meeting about meetings? My productivity is through the roof!",
    "Just got a ‘great’ performance review. Apparently, showing up is my strongest skill!",
    "Love how my email signature has more responsibilities than my job title.",
    "Can’t wait for this ‘quick update’ meeting to run longer than the actual project.",
    "Big thanks to the company for giving us free coffee instead of raises. Totally feeling appreciated!",
    "The boss just called my idea ‘interesting.’ That’s corporate speak for 'never happening.'",
    "Nothing like the thrill of being asked for ‘just one more revision’ at 5:30 PM on a Friday.",
    "We’re a family here! A dysfunctional, passive-aggressive family, but still a family!",
    "Love how ‘flexible hours’ really means ‘you’re always on call.’",
    "Another day of ‘thinking outside the box,’ while working in a tiny cubicle. Living the dream!",
    "Can’t wait to give my 110% for a company that gives me 3% raises!",
    "Just love how the ‘urgent task’ I dropped everything for is still sitting in someone’s inbox.",
    "Wow, who knew 'Do more with less' was code for 'Figure it out on your own.'",
    "The way my manager says 'We’re all in this together' makes me feel like I’m on a sinking ship.",
    "Nothing motivates me more than receiving an email about 'synergy' at 6 AM.",
    "I love how my suggestions turn into someone else’s brilliant idea!",
    "Another corporate buzzword-filled email? Just what I needed to spice up my day.",
    "My favorite part of working here is pretending the ping-pong table makes up for 12-hour days.",
    "Always great to see a new hire join and instantly get promoted over people who’ve been here for years.",
    "Training session on time management? Perfect timing—I didn’t have any time left anyway.",
    "Sure, I’ll ‘pivot’ again. Spinning in circles is basically my job description.",
    "Love when the company talks about ‘unlimited vacation’ but frowns if you actually use it.",
    "Another ‘working lunch’? Good thing I’m on a diet of stress and emails!",
    "The open-door policy is great—except when the door leads to more work.",
    "Nothing like last-minute feedback to make a 3-day project take 3 weeks!",
    "Oh, another restructuring? Let me guess—I’m still doing the same job but with a different title.",
    "Love how my ‘excellent performance’ comes with a pat on the back instead of a bonus.",
    "Can’t wait for the 3-hour meeting to plan the 10-minute task.",
    "Always reassuring when the team leader says, ‘Let’s wing it and see what happens!’",
    "Our company values transparency—just not when it comes to salaries, decisions, or promotions.",
    "Another team-building exercise? Finally, the chance to bond over awkward icebreakers!",
    "Love being the ‘go-to person’—especially when it means fixing everyone else’s mistakes.",
    "Oh, a surprise deadline? My favorite kind of surprise!",
    "Nothing beats the adrenaline rush of submitting work just for it to get buried in approvals.",
    "So glad we had a two-hour meeting to discuss something that could’ve been an email.",
    "Really appreciate how I’m ‘trusted to work independently’—aka, no one’s around to help.",
    "Always fun when a 'simple' task requires navigating 15 layers of bureaucracy.",
    "The best part of the day? Watching my to-do list grow faster than I can check things off.",
    "I’m amazed by how we manage to make the simplest projects unnecessarily complex.",
    "Who needs job perks when you have motivational posters in the breakroom?",
    "I just love the thrill of getting urgent emails marked 'high priority' at 4:59 PM.",
    "We’ve got so much ‘team spirit’ that I can practically hear the passive-aggression cheering us on.",
    "It’s so inspiring how every ‘urgent’ request magically becomes irrelevant the next day.",
    "Oh, the boss wants ‘creative ideas’? Guess I’ll just copy-paste last year’s!",
    "Nothing says 'we value you' like being voluntold to lead the holiday party planning committee.",
    "Loving the open-office concept—especially the part where I can’t concentrate at all.",
    "Why take vacation days when I can just work from a different location and call it a break?",
    "The annual survey is here again—time to give my ‘anonymous’ feedback no one reads.",
    "Performance reviews are great. I can’t wait to hear how much ‘room for improvement’ I have!",
    "Oh good, another initiative where the same old problems get a shiny new name.",
    "Big fan of how my work-life balance is 99% work and 1% dreaming of balance.",
    "Really enjoying the new workflow. It's like a scavenger hunt—except for information I actually need.",
    "Our strategy? Throw everything at the wall and hope something sticks.",
    "Who needs a raise when I can just work overtime for free?",
    "So exciting to see the boss take all the credit for our team’s hard work again!",
    "Loving the trust in the workplace—especially when it comes with micromanagement.",
    "It’s great how ‘open feedback’ sessions are just fancy words for a lecture.",
    "We’re really redefining innovation by doing the exact same thing over and over.",
    "Absolutely thrilled about the ‘new responsibilities’ that come with zero extra pay.",
    "Always inspired by our commitment to excellence, especially in dodging accountability.",
    "Oh, because working 60 hours a week is the dream I had as a kid!",
    "Another meeting that could have been an email? Sign me up!",
    "Wow, this unpaid internship will totally help me pay my rent. Thanks for the opportunity!",
    "Great, another task added to my plate. I was just thinking how bored I was!",
    "Sure, I'll work late again. It’s not like I had any plans or a life outside of work.",
    "Oh, yes, I absolutely love being micromanaged. It makes me feel so trusted!",
    "Wow, you need this yesterday? Lucky for you, I can manipulate time!",
    "Nothing beats the thrill of answering emails at 11 PM. Living the dream!",
    "Oh, another corporate wellness seminar? I'm sure this one will cure all my stress!",
    "I’m so lucky to be the only one who knows how to fix the copier. What an honor!",
    "Another strategic pivot? I’m sure this one will finally solve everything.",
    "Just love how ‘collaboration’ means being copied on emails for tasks I’m not involved in.",
    "Nothing like ‘employee engagement’ surveys to remind us how much we’re not being engaged.",
    "The best part about team celebrations? Watching the budget stretch for a single pizza slice each.",
    "Oh, another motivational quote in the breakroom? That should definitely fix morale.",
    "Love how ‘career development’ just means taking on more responsibilities for free.",
    "Another brainstorming session scheduled during lunch? How thoughtful!",
    "We’ve got a ‘lean team’? Translation: everyone’s doing three jobs now.",
    "Can’t wait to hear about the ‘exciting new changes’ that will make everything more confusing.",
    "The best thing about cross-department meetings is realizing how little we all understand each other.",
    "The boss is so good, he gave us three additional hours of unpaid work",
    # Non sarcastic
    "Excited to contribute to this new project with such an amazing team!",
    "Great to see leadership recognizing the hard work of the entire department!",
    "Just finished a productive brainstorming session—feeling inspired by everyone's ideas.",
    "Proud to have hit our quarterly targets. Amazing teamwork all around!",
    "Thankful for the mentorship and support I’ve received here—it’s been a great journey.",
    "Learning something new every day in this dynamic and challenging environment.",
    "Happy to collaborate with such talented and innovative colleagues!",
    "Our team’s dedication and focus continue to make a real difference. Keep it up!",
    "Thrilled to be part of a company that values employee development and growth.",
    "Looking forward to the next steps as we bring this project to life!",
    "Grateful to work for a company that invests in its people and their growth.",
    "Excited about the upcoming team-building activities—looking forward to connecting with everyone.",
    "Proud to be part of a project that’s making such a positive impact!",
    "Big thanks to leadership for recognizing and celebrating our hard work.",
    "It’s inspiring to work with people who are so dedicated and creative.",
    "Learning a lot from my team’s expertise every day—such a great environment!",
    "Looking forward to the new challenges this quarter—it’s going to be exciting!",
    "A huge shoutout to everyone who stayed late to ensure the project was a success!",
    "Feeling motivated by our company’s vision for the future!",
    "Thrilled to see our hard work translate into tangible results for the company.",
    "The collaboration and communication within the team are top-notch—great work, everyone!",
    "Thankful for a workplace that encourages innovation and thinking outside the box.",
    "It’s incredible to see how far we’ve come as a team—let’s keep it up!",
    "Feeling energized after today’s brainstorming session—so many great ideas!",
    "Happy to contribute to a workplace that values diversity and inclusivity.",
    "Appreciating the leadership’s openness and transparency during today’s meeting.",
    "It’s always rewarding to see how much our work positively impacts our clients.",
    "Shoutout to my mentor for their guidance—it’s made a huge difference in my journey.",
    "The company’s focus on employee well-being is truly appreciated—thank you!",
    "Excited to see what we can achieve together as a team in the months ahead.",
    "Grateful for a supportive team that encourages collaboration and creativity.",
    "Looking forward to the exciting challenges that lie ahead with this project.",
    "A huge thank-you to everyone who made this milestone possible—great teamwork!",
    "It’s amazing to see how our efforts are aligning with the company’s long-term vision.",
    "Excited to bring fresh ideas to the table and help drive positive change.",
    "I appreciate how much leadership values input from all levels of the organization.",
    "Working with this team has been a rewarding experience—I’m learning so much.",
    "Feeling inspired by the way our department tackled today’s challenges together.",
    "The new training session was really insightful—looking forward to applying what I learned.",
    "A big shoutout to the operations team for keeping everything running so smoothly!",
    "It’s rewarding to see our hard work making a tangible difference for our clients.",
    "I’m constantly impressed by the dedication and creativity of my colleagues.",
    "Feeling proud to work for a company that prioritizes community impact and sustainability.",
    "Excited to start this new project with such an enthusiastic and talented group.",
    "The recognition we received today is a testament to everyone’s commitment and passion.",
    "Thanks to leadership for encouraging open communication and transparency—it makes a difference.",
    "It’s great to see how collaboration across departments is helping us achieve our goals.",
    "I’m really appreciating the opportunities for personal and professional growth here.",
    "Today’s brainstorming session was packed with innovative ideas—can’t wait to see them in action!",
    "Feeling motivated by the company’s commitment to creating a positive work environment.",
    "The mentorship program has been incredibly helpful in shaping my career path—thank you!",
    "Celebrating the small wins today reminded me how much we can accomplish together.",
    "It’s been exciting to see how our new strategy is already producing great results.",
    "The leadership team’s vision and support make me optimistic about the future.",
    "Working on this cross-functional project has been a fantastic learning experience.",
    "Grateful to work somewhere that genuinely values and respects its employees.",
    "The way the team came together to tackle today’s challenges was nothing short of inspiring.",
    "Excited to take on a role where I can make a meaningful contribution to the company’s success.",
    "The new tools and processes we’ve implemented are really enhancing our productivity.",
    "Thanks to everyone for making this workplace such a positive and dynamic environment!",
    "Proud to see our team delivering such impressive results under tight deadlines.",
    "Grateful for the support from leadership during this challenging project.",
    "Excited to see the positive impact of our new initiative on customer satisfaction.",
    "It’s rewarding to watch our team’s hard work pay off in such meaningful ways.",
    "Looking forward to learning from our upcoming training session!",
    "Feeling inspired by the innovative solutions our team is coming up with.",
    "Thanks to everyone who made our recent launch a massive success!",
    "Proud to be part of an organization that genuinely values teamwork and collaboration.",
    "The mentorship program has been a game-changer for my career development—thank you!",
    "Excited to contribute to our company’s mission and make a difference in the industry.",
    "The boss is so good, it made a pizza party",
    "The boss was kind enough to explain what was wrong in our work",
    "Michael is a good teammate"
]

values = [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
]

print(len(comments))

tokenized_comments = tokenizer(comments, return_tensors="pt", truncation=True, padding=True, max_length=512)

model.eval()
with torch.no_grad():
    results = model(**tokenized_comments)

resulted_logits = results.logits
probabilities = torch.nn.functional.softmax(resulted_logits, dim=-1)
predicted_classes = torch.argmax(probabilities, dim=-1).numpy()

index = 0
for text, predicted_class, prob in zip(comments, predicted_classes, probabilities):
    response = "sarcastic" if predicted_class == 1 else "not sarcastic"
    value = values[index]
    index += 1
    print(f"Text: {text} Prediction: {response} Real value: {value} (Prob: {prob[predicted_class].item():.2f})")

metrics = {
    "accuracy": accuracy_score(values, predicted_classes),
    "precision": float(precision_score(values, predicted_classes)),
    "recall": float(recall_score(values, predicted_classes)),
    "f1_score": float(f1_score(values, predicted_classes))
}
print(metrics)